project_saya:
  outputs:
    dev:
      dataset: transformed_data
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /usr/local/airflow/dags/dbt/project_saya/file_json/your_bigquery_key.json
      location: US
      method: service-account
      priority: interactive
      project: myfarhan54875
      threads: 1
      type: bigquery
  target: dev
